# Generated by Django 2.0.2 on 2019-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191209_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fecha de Nacimiento (DD/MM/YYYY)'),
        ),
    ]
