# Generated by Django 2.0.2 on 2019-12-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('number', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'ahorros'), (2, 'corriente')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CuentaEmpresa',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Venta')),
                ('exchange_rate_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Compra')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Coin')),
            ],
            options={
                'verbose_name': 'TipoCambio',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Venta')),
                ('exchange_rate_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Compra')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('operation_number', models.CharField(max_length=20)),
                ('state', models.IntegerField(default=1, verbose_name=((1, 'iniciado'), (2, 'por confirmar'), (3, 'confirmado'), (4, 'completado'), (5, 'rechazado')))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bank_account', to='enterprise.BankAccount')),
                ('company_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_account', to='enterprise.BankAccount')),
                ('convert_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convert_from', to='enterprise.Coin')),
                ('convert_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convert_to', to='enterprise.Coin')),
            ],
            options={
                'verbose_name': 'Transaccion',
            },
        ),
    ]
