# Generated by Django 2.0.2 on 2019-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20191209_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='coin',
        ),
        migrations.AddField(
            model_name='coin',
            name='exchange_rate_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='exchange_rate_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Venta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
