# Generated by Django 2.0.2 on 2019-12-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20191209_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='convert_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='convert_to',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate_purchase',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate_sale',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin_transform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coin_transform', to='enterprise.Coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Exchange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
